# Generated by Django 5.0.8 on 2024-08-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма задолженности')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to='company.company', verbose_name='Кому должен')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debtor', to='company.company', verbose_name='Кто должен')),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженности',
                'ordering': ('id',),
            },
        ),
    ]
